### ISSUE TITLE
"Bad CPU type in executable" when installed on Apple Silicon Mac

### ISSUE THREAD

**Issue by martinklepsch** [greglook/cljstyle#100]
Hello,

I've just moved to a new mac and noticed that cljstyle doesn't seem to run on Apple M1/M2 chips, the following error being shown:

```
exec: Failed to execute process '/opt/homebrew/bin/cljstyle': Bad CPU type in executable.
```
This is with `v.0.15.0` freshly installed via `brew install --cask cljstyle`.

Is Rosetta required for cljstyle for now?

**Comment by AbhinavOmprakash** [comment]
@martinklepsch I faced the same issue, after installing rosetta it started working.
rosetta can be installed with 
```
softwareupdate --install-rosetta
```

**Comment by greglook** [comment]
Release 0.16.626 has an `arm64` platform native binary now that I have an M2 mac to build on. 🎉 I'll follow with an update to the homebrew recipe for `cljstyle`.

**Comment by greglook** [comment]
Someone beat me to it! https://github.com/Homebrew/homebrew-cask/commit/bbccdac5ed8553c168872654c6bff155b8d5fea5

**Comment by DeLaGuardo** [comment]
Looks like this is still a problem when installed on Github's macos action runner: https://github.com/DeLaGuardo/setup-clojure/actions/runs/11683288302/job/32532176812
