### ISSUE TITLE
Binary doesn't work on the latest macOS GitHub Action Runner machines

### ISSUE THREAD

**Issue by DeLaGuardo** [greglook/cljstyle#106]
> The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

https://github.com/DeLaGuardo/setup-clojure/actions/runs/7846032256/job/21411974609?pr=104#step:5:17

**Comment by greglook** [comment]
This seems like a CPU architecture issue - I've changed it to build with `compatibility`, which should hopefully address this in the next release.

**Comment by greglook** [comment]
Please try this with the latest release [0.17.642](https://github.com/greglook/cljstyle/releases/tag/0.17.642), which is built for compatibility with more CPU architectures.

**Comment by DeLaGuardo** [comment]
Latest version works flawlessly, thank you!
