### ISSUE TITLE
Want you to consider rename this library

### ISSUE THREAD

**Issue by makinoshi** [greglook/cljstyle#18]
Thank you for your great improvements.

I consider to use it as standard formatter for whole products in my company.
But the name of `cljfmt` cause some awkward situations such as following.

- Make it difficult to find this repo from google search or Clojars
- Name collision in the [Vim ALE](https://github.com/dense-analysis/ale/tree/master/ale_linters/clojure)

Do you have the possibility of renaming it?

**Comment by greglook** [comment]
I'm open to the idea of renaming this project, since it's basically a new tool at this point. I haven't thought of good alternative names yet though, `cljfmt` is pretty compelling.

**Comment by greglook** [comment]
The project (and the resulting binary) is now named `cljstyle`.

**Comment by makinoshi** [comment]
@greglook I want to thank you for your great choice and bless the `cljstyle` future that is given very nice name!
