### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by dharrigan** [greglook/cljstyle#27]
Hi Greg,

I'm looking to package up this utility for Arch (I already maintain a few others, like clj-kondo and babashka). Is there a license for this utility? I can't seem to see it in the README or in the source.

Thanks.

-=david=-

**Comment by greglook** [comment]
This inherits the EPL from the original `cljfmt` project, so I've added the license file in b3c3c766003c103051caf3218f4636e62b6ace2c.

**Comment by dharrigan** [comment]
Hi,

Thanks! I've added the package to Arch Linux now:

https://aur.archlinux.org/packages/cljstyle-bin/

-=david=-
