### ISSUE TITLE
Keep ns :require (and others) linebreaks

### ISSUE THREAD

**Issue by Deraen** [greglook/cljstyle#35]
I like to keep the first require at the same line with `:require` form:

```clj
(ns example.foo
  (:require [reagent.core :as r]
            [re-frame.core :as rf]))
```

Currently cljstyle adds linebreak after `:require`. I'd like to use the ns formatting, but keeping existing linebreaks.

**Comment by greglook** [comment]
The way `cljstyle` formats namespaces is to structurally parse and fully rewrite them, so it's not currently possible for it to "preserve" all line breaks. It seems like what you want may just be to start the libspecs on the same line as the `:require` keyword - if that's sufficient, I can add a formatting option for that.
