### ISSUE TITLE
Setup via brew

### ISSUE THREAD

**Issue by just-sultanov** [greglook/cljstyle#36]
Hi! 
Thanks for the library. 🔥
Any plans for installing with `brew`? It would be great.

**Comment by greglook** [comment]
Hey, glad you're getting use out of the tool! I haven't looked into packaging via homebrew, but that certainly seems useful.

**Comment by robhanlon22** [comment]
@greglook PR against `homebrew-cask` here: https://github.com/Homebrew/homebrew-cask/pull/80734

**Comment by greglook** [comment]
Great! Will follow along.

**Comment by robhanlon22** [comment]
@greglook README.md update in #42!
