### ISSUE TITLE
Multi arity functions indentation has extra space

### ISSUE THREAD

**Issue by felipethome** [greglook/cljstyle#46]
After running `check` this is the result for multiple arity functions:

```clj
 (defn a
   ([x]
-   (a x 2))
+    (a x 2))
   ([x y]
-   (* x y)))
+    (* x y)))
```

Is this the expected behavior? 

https://github.com/bbatsov/clojure-style-guide#multiple-arity-indentation

**Comment by greglook** [comment]
This seems like a bug, but I can't reproduce it. What version are you running, and what configuration are you setting?
```
% cljstyle version
mvxcvi/cljstyle 0.12.1 (da04c9f4b2167749918bd8bea4e3fd0f3bd5e2ed)

% cljstyle pipe
(defn a
  ([x]
   (a x 2))
  ([x y]
   (* x y)))
^D
(defn a
  ([x]
   (a x 2))
  ([x y]
   (* x y)))
```

**Comment by felipethome** [comment]
This happened after I replaced every indentation with `[[:inner 0]]`. I will get the version and config and post here.

**Comment by greglook** [comment]
Please reopen if this is still an issue.
