### ISSUE TITLE
Publish to Clojars

### ISSUE THREAD

**Issue by robhanlon22** [greglook/cljstyle#53]
While not as performant as the GraalVM-built binary, publishing cljstyle to Clojars would make integration with existing Clojure build tooling quite a bit easier, and would be well-suited to CI environments. What do you think?

**Comment by greglook** [comment]
That's a great use-case, I hadn't considered using it from an alias/profile in leiningen! I'll publish the current release and make sure to publish them going forward.

**Comment by greglook** [comment]
Did this, added instructions in f5eecefc3e86853b1999b0dd31810b77628018be.
