### ISSUE TITLE
Static Build?

### ISSUE THREAD

**Issue by socksy** [greglook/cljstyle#65]
I saw from the readme: "The native binaries are self-contained, so to install them simply place them on your path." which perked my attention, so I tried a binary on my NixOS box, but (as usual with NixOS) it fails to run with "no such file or directory", which means that it's dynamically linked (apparently it is only `libz` that I was missing on my platform, but for various reasons that's non trivial to get working in the system. 

According to https://www.graalvm.org/reference-manual/native-image/StaticImages/ it should be possible to make a static image by passing in `--static` to the `native-image` call. I would make a PR to do that, but since I don't have a running version of graalvm I wouldn't be able to test it. Perhaps it's worth a try?

**Comment by greglook** [comment]
This should certainly be possible - I've been meaning to automate the image building process anyway, so I'll add a statically-compiled linux version to the list of things to build.

**Comment by greglook** [comment]
[0.15.0](https://github.com/greglook/cljstyle/releases/tag/0.15.0) has a static linux binary.
