### ISSUE TITLE
Support shebang

### ISSUE THREAD

**Issue by ne-sachirou** [greglook/cljstyle#70]
Some Clojure files have shebang like `#!/usr/bin/env clj -M` or `#!/usr/bin/env bb` (it's https://github.com/babashka/babashka ). cljstyle can't process these files with `clojure.lang.ExceptionInfo: Invalid symbol: !/usr/bin/env.`. When the first line starts with `#!` it would be a shebang so it'll be ignored.

**Comment by suryaaditya** [comment]
#!/usr/bin/env bb 
babashka scripts have these, and cljstyle fails.
