### ISSUE TITLE
--overwrite not supported on macOS tar

### ISSUE THREAD

**Issue by martinklepsch** [greglook/cljstyle#75]
Not sure what the ideal solution here is but Mac's `tar` command does not support the `--overwrite` option. 

## Workaround

h/t to @alexdao3 for this

When running `./install-cljstyle`, you may get the following error on Mac:

   tar: Option --overwrite is not supported"

If so, open the `install-cljstyle` file and remove the `--overwrite` option. Then re-run the `./install-cljstyle` command.
This should install the `cljstyle` binary into your `/usr/local/bin` directory.

**Comment by greglook** [comment]
Thanks for the report. The script can probably detect the OS and do the right thing here.

**Comment by greglook** [comment]
Release 0.16.626 switches to the zip artifacts, so this shouldn't be an issue anymore.
