### ISSUE TITLE
Allow indent-size to be overridden

### ISSUE THREAD

**Issue by dharrigan** [greglook/cljstyle#8]
Hi,

I notice that the default indent size (in `indent.clj`) is `2`. There does not appear to be a way to change this (afaik). According to this guide, [clojure style guide](https://guide.clojure.style/#one-space-indent), 2 space indents are bad.

Whilst I'm *not* advocating changing the indent-size to 1, please can we have the ability to change the indent size to 1 if we choose to do so :-)

Thank you.

-=david=-

**Comment by greglook** [comment]
This should be possible in the new 0.10.0 release using `:list-indent-size`.
