### ISSUE TITLE
Increasing file line-length or column length above 80

### ISSUE THREAD

**Issue by dviramontes** [greglook/cljstyle#84]
Hi, having some trouble figuring out how to increase the overall line-length or column length per file above 80 columns. Any pointers would be great. 

My use-case - 
trying to avoid indentation like this:
```clojure 
(let 
  [x 
     (fn [] ...)]
```

and would prefer indentation like this for let bindings
```clojure
(let [x (fn [] ...)]
```

Less stair, more horizontal width if that makes sense. Preferably 120 columns. Thank you!

**Comment by greglook** [comment]
cljstyle doesn't currently enforce any rules around line length; is it doing something you don't expect it to?
