### ISSUE TITLE
Running cljfmt with all rules disabled still produces diffs

### ISSUE THREAD

**Issue by drewinglis** [greglook/cljstyle#9]
The most notable diff is that for named functions it doesn't allow the arguments list to stay on the same line:

```
$ cljfmt check foo.clj 
--- a/foo.clj
+++ b/foo.clj
@@ -1,2 +1,3 @@
-(fn foo [arg-one]
+(fn foo
+[arg-one]
   nil)
1 files formatted incorrectly
$ cat foo.clj 
(fn foo [arg-one]
  nil)
```

**Comment by greglook** [comment]
`:line-break-functions?` controls this behavior and wasn't disabled by your config. It was also missing from the README. Added in 7c5d943762a6ce4e82c8a14fae0db100bccb0844.

**Comment by greglook** [comment]
I wonder if it's worth adding a `--no-defaults` option to the CLI to better support this sort of isolation. 🤔

**Comment by drewinglis** [comment]
I'm fine with closing this out with the resolution being "fixed docs". I think as long as you give the user a way to run it with everything turned off then that's fine. I don't think a special option is needed, though I would probably still use it.
